version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_${APP_NAME}
    restart: 'no'
    depends_on:
      - phpfpm
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ${PROJECT_DIR}:/var/www
    environment:
      WEB_ROOT: ${WEB_ROOT}
      PHP_HOST: phpfpm
    networks:
      - default

  phpfpm:
    build:
      context: ./phpfpm/
      dockerfile: Dockerfile
    container_name: phpfpm_${APP_NAME}
    restart: 'no'
    depends_on:
      - postgres
    volumes:
      - ${PROJECT_DIR}:/var/www
      - ./phpfpm/php.ini:/etc/php/8.1/php.ini
      - ./phpfpm/pools/www.conf:/etc/php/8.1/fpm/pool.d/www.conf
      - ./phpfpm/xdebug.ini:/etc/php/8.1/mods-available/xdebug.ini
      - ./phpfpm/supervisor.conf:/etc/supervisor/supervisor_nodeamon.conf
    environment:
      XDEBUG_PORT: ${XDEBUG_PORT}
      XDEBUG_HOST: ${XDEBUG_HOST}
      XDEBUG_IDE: ${XDEBUG_IDE}
    env_file: .env
    working_dir: /var/www
    networks:
      - default
    extra_hosts:
      docker: ${DOCKER_HOST_IP}

  postgres:
    image: postgres:14-alpine
    container_name: postgres_${APP_NAME}
    restart: 'no'
    ports:
      - ${PG_PORT}:5432
    volumes:
      - pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    networks:
      - default
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: 'no'
    container_name: pgadmin_${APP_NAME}
    ports:
        - ${PG_ADMIN_PORT}:${PG_ADMIN_PORT}
    volumes:
        - pgadmin:/var/lib/pgadmin
    environment:
        PGADMIN_LISTEN_PORT: ${PG_ADMIN_PORT}
        PGADMIN_DEFAULT_EMAIL: ${EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}

volumes:
  pgsql:
    name: pgsql_${APP_NAME}
    external: false
  pgadmin:
    name: pgadmin_${APP_NAME}
    external: false
networks:
  default:
    name: ${APP_NAME}_network
